builds:
  - binary: check-cert-net
    goos:
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
     - -X main.Version={{.Version}}
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: kazeburo
    name: check-cert-net
